version: "3.8"

services:
  xlazar15-postgres-db:
    image: postgres:13
    container_name: xlazar15-db-postgres
    restart: unless-stopped
    mem_limit: 1536MB
    mem_reservation: 1G
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_USER:-db-pentesting}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db_xlazar15_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - xlazar15-pentesting
  xlazar15-db-pgadmin4:
    image: dpage/pgadmin4:6.1
    container_name: xlazar15-db-pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: xlazar15@vut.cz
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5080:80
    depends_on:
      - xlazar15-postgres-db
    networks:
      - xlazar15-pentesting
  flyway:
    image: flyway/flyway:8
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_URL=jdbc:postgresql://xlazar15-postgres-db:5432/db-pentesting
      - FLYWAY_SCHEMAS=public
    command: -locations=filesystem:/flyway/sql -connectRetries=300 migrate
    volumes:
      - ./db/migration/postgresql:/flyway/sql
    depends_on:
      - xlazar15-postgres-db
    networks:
      - xlazar15-pentesting
  nginx:
    image: nginx:1.21.3
    container_name: xlazar15-xnginx
    restart: unless-stopped
    volumes:
      - ./configuration/nginx-reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - xlazar15-pentesting
volumes:
  db_xlazar15_data:
    name: postgre-db-xlazar15-data
networks:
  xlazar15-pentesting:
    name: xlazar15-pentesting
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
