version: "3.9"

services:
  xlazar15-postgres-db:
    image: postgres:14
    container_name: xlazar15-db-postgres
    restart: unless-stopped
    mem_limit: 1536MB
    mem_reservation: 1G
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_USER:-db-pentesting}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db_xlazar15_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - xlazar15-pentesting
  xlazar15-postgres-backup:
    container_name: xlazar15-db-backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    networks:
      - xlazar15-pentesting
    depends_on:
      - xlazar15-postgres-db
    environment:
      - POSTGRES_HOST=xlazar15-db-postgres
      - POSTGRES_DB=${POSTGRES_USER:-db-pentesting}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_USER:-postgres}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=bds --blobs
      - SCHEDULE=@every 24h00m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81
  xlazar15-db-pgadmin4:
    image: dpage/pgadmin4:6.1
    container_name: xlazar15-db-pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: xlazar15@vut.cz
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5080:80
    networks:
      - xlazar15-pentesting
    depends_on:
      - xlazar15-postgres-db
  web:
    container_name: xlazar15-web
    restart: always
    build: ./app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn --certfile=./certs/cert.pem --keyfile=./certs/cert.key bds.wsgi:application --bind 0.0.0.0:443"
    volumes:
      - ./app/:/usr/src/app/
      - ./config/nginx/certs/:/usr/src/app/certs
    ports:
      - 8000:8000
    networks:
      - xlazar15-pentesting
    env_file:
      - ./config/web/.env.dev
    depends_on:
      - xlazar15-postgres-db
  nginx:
    image: nginx:latest
    container_name: xlazar15-xnginx
    restart: unless-stopped
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/certs/:/etc/nginx/conf.d/certs
    ports:
      - 443:443
      - 80:80
    networks:
      - xlazar15-pentesting
    depends_on:
      - web
  flyway:
    image: flyway/flyway:8.1.0
    container_name: xlazar15-flyway
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_URL=jdbc:postgresql://xlazar15-postgres-db:5432/db-pentesting
      - FLYWAY_SCHEMAS=bds
    command: -locations=filesystem:/flyway/sql -connectRetries=300 migrate
    volumes:
      - ./db/migration/postgresql:/flyway/sql
    depends_on:
      - web
    networks:
      - xlazar15-pentesting
volumes:
  db_xlazar15_data:
    name: postgre-db-xlazar15-data
networks:
  xlazar15-pentesting:
    name: xlazar15-pentesting
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
